version: "3.7"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  app:
    build:
      context: .
    container_name: DJANGOXDOCKERNAME
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/ecommerce
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
    depends_on:
      - db
#  nginx:
#    image: nginx:latest
#    container_name: NGINXDOCKERNAME
#    ports:
#      - "8000:8000"
#    volumes:
#      - .:/ecommerce
#      - ./proxy/nginx:/etc/nginx/conf.d
#      - ./static_in_env:/static_in_env
#    depends_on:
#      - app
